server:
  port: 8089
spring:
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
#  日期返回 yyyy-MM-dd HH:mm:ss
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  # redis 配置
#  redis:
#    # 地址
#    host: 192.168.85.129
#    # 端口，默认为6379
#    port: 6379
#    # 密码
#    password:
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ckss.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 全局配置
  configuration:
    #    驼峰式命名
    map-underscore-to-camel-case: true
    #    全局映射器启用缓存
    cache-enabled: true
    #     允许 JDBC 支持自动生成主键
    use-generated-keys: true
    #    配置默认的执行器
    default-executor-type: reuse
    #     指定 MyBatis 所用日志的具体实现
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 日志配置
logging:
  level:
    com.ckss: debug
    org.springframework: warn

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



##达达配送配置信息
dada:
  config:
    appKey: you_key
    appSecret: you_secret
    host: http://newopen.qa.imdada.cn    #请求地址  测试环境
    sourceId: 73753         #商户ID 测试ID
    format: json
    v: 1.0
    cityCode: 023
    shopNo: 11047059
    callbackUrl: http://cksspk.free.idcfengye.com/dada/callback
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


